name: Check base docker image update

on:
  schedule:
    - cron:  '4 4 * * 6'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: ghcr.io/nginxinc/nginx-unprivileged:latest
          image: ghcr.io/krkabol/nginx-noroot-fpmsocket:latest

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/krkabol/nginx-noroot-fpmsocket:latest
        if: steps.check.outputs.needs-updating == 'true'